#!/bin/bash

numberOfArguments=$#
declare -a scores
commandLineArray=( "$a" )

if [[ -z $1 || -z $2 || -z $3 ]];then
	echo
	echo "Usage: <first name> <last name> <test score> ..."
	exit
else 
	fname=$1
	lname=$2
	scores[0]=$3
	
	for (( i = 4, j = 1; i < $numberOfArguments; i++, jj++ ))
	do 
		scores[$j]=$commandLineArray[$i]  
	done
fi

echo ${scores[1]}


